package com.glintt.cvm.model;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;

import javax.persistence.Entity;

import org.hr_xml._3.CountryCodeEnumType;
import org.hr_xml._3.GenderCodeEnumType;
import org.hr_xml._3.LanguageCodeEnumType;
import org.hr_xml._3.MaritalStatusCodeEnumType;
import org.hr_xml._3.ResourceRelationshipCodeEnumType;

import com.glintt.cvm.model.PersonContacts.Email;
import com.glintt.cvm.model.PersonContacts.MobilePhone;
import com.glintt.cvm.model.PersonContacts.Telephone;
import com.glintt.cvm.model.PersonalInfo.BirthInfo;
import com.glintt.cvm.model.PersonalInfo.PersonContactsProfile;
import com.glintt.cvm.model.ProfessionalInfo.Certification;
import com.glintt.cvm.model.ProfessionalInfo.Certification.IssuingAuthority;
import com.glintt.cvm.model.ProfessionalInfo.Contributor;
import com.glintt.cvm.model.ProfessionalInfo.Copyright;
import com.glintt.cvm.model.ProfessionalInfo.Employer;
import com.glintt.cvm.model.ProfessionalInfo.Position;
import com.glintt.cvm.model.ProfessionalInfo.PublicationProfileCode;
import com.glintt.cvm.model.ProfessionalInfo.TimePeriod;
import com.glintt.cvm.model.Publication.Article;
import com.glintt.cvm.model.Publication.Book;
import com.glintt.cvm.model.Publication.ConferencePaper;
import com.glintt.cvm.model.Publication.UnspecifiedPublication;

@Entity
public class TestPerson extends Person {
    private static final long serialVersionUID = 8579660817063564713L;

    @SuppressWarnings("deprecation")
    public TestPerson() {
        super(LanguageCodeEnumType.PT);
        PersonalInfo personalInfo = new PersonalInfo();

        personalInfo.setName(new PersonName("João", "Oliveira Silva"));
        personalInfo.setFatherName(new PersonName("António", "Silva"));
        personalInfo.setMotherName(new PersonName("Maria", "Oliveira"));

        personalInfo.setGender(GenderCodeEnumType.MALE);
        personalInfo.setMaritalStatus(MaritalStatusCodeEnumType.MARRIED);
        personalInfo.setCitizenshipCountry(CountryCodeEnumType.PT);
        personalInfo.setPrimaryLanguage(LanguageCodeEnumType.PT);

        BirthInfo birthInfo = new PersonalInfo.BirthInfo();
        Location birthLocation = new Location();
        Calendar birthDate = Calendar.getInstance();
        birthDate.set(1970, 1, 1);
        birthInfo.setBirthDate(birthDate.getTime());
        birthLocation.setCountry(CountryCodeEnumType.PT);
        birthLocation.setCountryDivision("Sintra");
        birthLocation.setCity("Queluz");
        birthInfo.setBirthLocation(birthLocation);
        personalInfo.setBirthInfo(birthInfo);

        PersonContacts personalProfile = new PersonContacts();
        personalProfile.setContactsProfile(PersonContactsProfile.PERSONAL);
        Address personalAddress = new Address();
        personalAddress.setStreetName("Rua da Palma");
        personalAddress.setBuildingName("C.C. Martim Moniz");
        personalAddress.setBuildingNumber("N.º 2");
        personalAddress.setFloor("Loja 3");
        personalAddress.setCity("Lisboa");
        personalAddress.setCountry(CountryCodeEnumType.PT);
        personalAddress.setPostalCode("1100-111");
        personalAddress.setPostOfficeBox("LISBOA");
        personalProfile.setAddress(personalAddress);
        Email personalEmail = new PersonContacts.Email();
        personalEmail.setEmailAddress("joao.silva@somedomain.net");
        personalProfile.setEmail(personalEmail);
        MobilePhone personalMobile = new PersonContacts.MobilePhone();
        personalMobile.setCountryDialing("351");
        personalMobile.setDialNumber("911 111 111");
        personalProfile.setMobilePhone(personalMobile);
        personalInfo.addPersonContacts(personalProfile);
        Telephone personalTelephone = new PersonContacts.Telephone();
        personalTelephone.setCountryDialing("351");
        personalTelephone.setDialNumber("212 345 678");
        personalProfile.setTelephone(personalTelephone);

        PersonContacts businessProfile = new PersonContacts();
        businessProfile.setContactsProfile(PersonContactsProfile.BUSINESS);
        MobilePhone businessMobile = new PersonContacts.MobilePhone();
        businessMobile.setCountryDialing("351");
        businessMobile.setDialNumber("922 222 222");
        businessProfile.setMobilePhone(businessMobile);
        personalInfo.addPersonContacts(businessProfile);

        ProfessionalInfo professionalInfo = new ProfessionalInfo();

        professionalInfo.setProfileName("Sample CV generated from curricula WebApp");
        professionalInfo.setExecutiveSummary("executive summary text...");

        Collection<Certification> certifications = new ArrayList<Certification>();
        Certification certification1 = new Certification();
        certification1.setName("nome da certificação 1");
        Calendar cert1issuedate = Calendar.getInstance();
        certification1.setIssueDate(cert1issuedate.getTime());
        IssuingAuthority ia1 = new IssuingAuthority();
        ia1.setName("issuing authority 1");
        Location ia1Location = new Location();
        ia1Location.setCountry(CountryCodeEnumType.PT);
        ia1Location.setCity("Lisboa");
        ia1Location.setPostalCode("1100-002 LISBOA");
        ia1.setLocation(ia1Location);
        certification1.setIssuingAuthority(ia1);
        certifications.add(certification1);
        Certification certification2 = new Certification();
        certification2.setName("nome da certificação 2");
        IssuingAuthority ia2 = new IssuingAuthority();
        ia2.setName("issuing authority 2");
        Location ia2Location = new Location();
        ia2Location.setCountry(CountryCodeEnumType.ES);
        ia2Location.setCity("Madrid");
        ia2.setLocation(ia2Location);
        certification2.setIssuingAuthority(ia2);
        certifications.add(certification2);
        professionalInfo.setCertifications(certifications);

        Collection<Publication> publications = new ArrayList<Publication>();
        Copyright exampleCopyright = new Copyright();
        exampleCopyright.setYear("2011");
        exampleCopyright.setText("all rights reserved");
        Collection<Contributor> exampleContributors = new ArrayList<Contributor>();
        Contributor contributor1 = new Contributor();
        contributor1.setName(new PersonName("Herman", "José"));
        contributor1.setRole("co-author");
        exampleContributors.add(contributor1);
        Contributor contributor2 = new Contributor();
        contributor2.setName(new PersonName("Camilo", "de Oliveira"));
        contributor2.setRole("ilustrador");
        exampleContributors.add(contributor2);
        Article articleContent = new Article();
        articleContent.setTitle("article title");
        Calendar articledate = Calendar.getInstance();
        articleContent.setDate(articledate.getTime());
        articleContent.setAbstractText("abstract text of article");
        articleContent.setComment("comment for the article");
        articleContent.setIssn("1534-0481");
        articleContent.setCopyright(exampleCopyright);
        articleContent.setContributors(exampleContributors);
        articleContent.setJournalName("Diário de Notícias");
        articleContent.setVolume("III");
        articleContent.setIssue("343/2011");
        articleContent.setPageNumbers("1-3, 12, 48-51");
        articleContent.setLanguage(LanguageCodeEnumType.FR);
        Publication article = new Publication();
        article.setType(PublicationProfileCode.ARTICLE);
        article.setInfo(articleContent);
        article.setDescription("article description");
        publications.add(article);
        Publication nullArticle = new Publication();
        nullArticle.setType(PublicationProfileCode.ARTICLE);
        // publications.add(nullArticle);
        Publication emptyArticle = new Publication();
        emptyArticle.setType(PublicationProfileCode.ARTICLE);
        emptyArticle.setInfo(new Article());
        publications.add(emptyArticle);
        UnspecifiedPublication otherContent = new UnspecifiedPublication();
        otherContent.setTitle("unspecified title");
        Calendar othercontentdate = Calendar.getInstance();
        otherContent.setDate(othercontentdate.getTime());
        otherContent.setAbstractText("abstract text of unspecified");
        otherContent.setComment("comment for the unspecified");
        otherContent.setIssn("1234-5678");
        otherContent.setIsbn("1234567890");
        otherContent.setNumberOfPages(34);
        otherContent.setPublisherName("editor para unspecified");
        Location exampleLocation = new Location();
        exampleLocation.setCountry(CountryCodeEnumType.PT);
        exampleLocation.setCity("Lisboa");
        otherContent.setPublisherLocation(exampleLocation);
        Publication other = new Publication();
        other.setType(PublicationProfileCode.UNSPECIFIED);
        other.setInfo(otherContent);
        publications.add(other);
        Publication nullOther = new Publication();
        nullOther.setType(PublicationProfileCode.UNSPECIFIED);
        // publications.add(nullOther);
        Publication emptyOther = new Publication();
        emptyOther.setType(PublicationProfileCode.UNSPECIFIED);
        emptyOther.setInfo(new UnspecifiedPublication());
        publications.add(nullOther);
        Book bookContent = new Book();
        bookContent.setTitle("book title");
        Calendar bookcontentdate = Calendar.getInstance();
        bookContent.setDate(bookcontentdate.getTime());
        bookContent.setAbstractText("abstract text of book");
        bookContent.setComment("comment for the book");
        bookContent.setIssn("1234-5678");
        bookContent.setIsbn("1234567890");
        bookContent.setEdition("1st.");
        bookContent.setChapter("4");
        Publication book = new Publication();
        book.setType(PublicationProfileCode.BOOK);
        book.setInfo(bookContent);
        book.setDescription("book description");
        publications.add(book);
        Publication nullBook = new Publication();
        nullBook.setType(PublicationProfileCode.BOOK);
        // publications.add(nullBook);
        Publication emptyBook = new Publication();
        emptyBook.setType(PublicationProfileCode.BOOK);
        emptyBook.setInfo(new Book());
        publications.add(emptyBook);
        ConferencePaper paperContent = new ConferencePaper();
        paperContent.setTitle("conference paper title");
        Calendar papercontentdate = Calendar.getInstance();
        paperContent.setDate(papercontentdate.getTime());
        paperContent.setAbstractText("abstract text of conference paper");
        paperContent.setComment("comment for the conference paper");
        paperContent.setEventName("event name");
        Calendar papereventdate = Calendar.getInstance();
        paperContent.setEventDate(papereventdate.getTime());
        paperContent.setEventLocationName("pavilhão atlântico");
        paperContent.setEventLocation(exampleLocation);
        Publication paper = new Publication();
        paper.setType(PublicationProfileCode.CONFERENCE_PAPER);
        paper.setInfo(paperContent);
        paper.setDescription("conference paper description");
        publications.add(paper);
        Publication nullPaper = new Publication();
        nullPaper.setType(PublicationProfileCode.CONFERENCE_PAPER);
        // publications.add(nullPaper);
        Publication emptyPaper = new Publication();
        emptyPaper.setType(PublicationProfileCode.CONFERENCE_PAPER);
        emptyPaper.setInfo(new ConferencePaper());
        publications.add(emptyPaper);
        professionalInfo.setPublications(publications);

        Collection<Employer> employers = new ArrayList<Employer>();
        Employer employer1 = new Employer();
        employer1.setName("Employer 1");
        employer1.setUrl("http://www.employer1.com");
        employer1.setHeadcount("100");
        OrganizationContacts organizationContacts = new OrganizationContacts();
        organizationContacts.setName(new PersonName("Maria Deolinda", "Pereira"));
        organizationContacts.setRole("gestora de recursos humanos");
        organizationContacts.setMobilePhone(businessMobile);
        organizationContacts.setEmail(personalEmail);
        employer1.setContacts(organizationContacts);
        TimePeriod tp1 = new TimePeriod();
        Calendar tp1startdate = Calendar.getInstance();
        tp1startdate.set(2010, 1, 1);
        tp1.setStartDate(tp1startdate.getTime());
        Calendar tp1enddate = Calendar.getInstance();
        tp1enddate.set(2010, 12, 31);
        tp1.setEndDate(tp1enddate.getTime());
        employer1.setEmploymentPeriod(tp1);
        Collection<Position> employer1Positions = new ArrayList<Position>();
        Position position1 = new Position();
        position1.setTitle("position 1");
        position1.setDescription("description for position 1");
        position1.setRelationshipType(ResourceRelationshipCodeEnumType.EMPLOYEE);
        position1.setUnitName("unit name for position 1");
        position1.setAddress(personalAddress);
        position1.setEmploymentPeriod(tp1);
        employer1Positions.add(position1);
        Position position2 = new Position();
        position2.setTitle("position 2");
        position2.setDescription("description for position 2");
        position2.setRelationshipType(ResourceRelationshipCodeEnumType.VENDOR_EMPLOYEE);
        position2.setUnitName("unit name for position 2");
        employer1Positions.add(position2);
        employer1.setPositions(employer1Positions);
        employers.add(employer1);
        Employer employer2 = new Employer();
        employer2.setName("Employer 2");
        employer2.setUrl("http://www.employer2.com");
        employer2.setHeadcount("10000");
        TimePeriod tp2 = new TimePeriod();
        Calendar tp2startdate = Calendar.getInstance();
        tp2startdate.set(2010, 12, 31);
        tp2.setStartDate(tp2startdate.getTime());
        employer2.setEmploymentPeriod(tp2);
        employers.add(employer2);
        professionalInfo.setEmployers(employers);

        this.setPersonalInfo(personalInfo);
        this.setProfessionalInfo(professionalInfo);

    }
}
