package com.glintt.cvm.ui.pages;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class TestPage extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7711327011240262859L;
	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Accordion actions;
	@AutoGenerated
	private Label ccc;
	@AutoGenerated
	private Label bbb;
	@AutoGenerated
	private Label aaa;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TestPage() {
		buildMainLayout();
		setCompositionRoot(this.mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		this.mainLayout = new HorizontalLayout();
		this.mainLayout.setImmediate(false);
		this.mainLayout.setWidth("100%");
		this.mainLayout.setHeight("100%");
		this.mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// actions
		this.actions = buildActions();
		this.mainLayout.addComponent(this.actions);

		// panel_1
		this.panel_1 = buildPanel_1();
		this.mainLayout.addComponent(this.panel_1);

		return this.mainLayout;
	}

	@AutoGenerated
	private Accordion buildActions() {
		// common part: create layout
		this.actions = new Accordion();
		this.actions.setImmediate(false);
		this.actions.setWidth("12.0em");
		this.actions.setHeight("100.0%");

		// aaa
		this.aaa = new Label();
		this.aaa.setImmediate(false);
		this.aaa.setWidth("-1px");
		this.aaa.setHeight("-1px");
		this.aaa.setValue("Label");
		this.actions.addTab(this.aaa, "Action A", null);

		// bbb
		this.bbb = new Label();
		this.bbb.setImmediate(false);
		this.bbb.setWidth("-1px");
		this.bbb.setHeight("-1px");
		this.bbb.setValue("Label");
		this.actions.addTab(this.bbb, "Action B", null);

		// ccc
		this.ccc = new Label();
		this.ccc.setImmediate(false);
		this.ccc.setWidth("-1px");
		this.ccc.setHeight("-1px");
		this.ccc.setValue("Label");
		this.actions.addTab(this.ccc, "Action C", null);

		return this.actions;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		this.panel_1 = new Panel();
		this.panel_1.setImmediate(false);
		this.panel_1.setWidth("100.0%");
		this.panel_1.setHeight("100.0%");

		// verticalLayout_1
		this.verticalLayout_1 = new VerticalLayout();
		this.verticalLayout_1.setImmediate(false);
		this.verticalLayout_1.setWidth("100.0%");
		this.verticalLayout_1.setHeight("100.0%");
		this.verticalLayout_1.setMargin(false);
		this.panel_1.setContent(this.verticalLayout_1);

		return this.panel_1;
	}

}
